name: Build Vue and Electron App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # 当打标签时触发（例如 v1.0.0）
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 来构建

    strategy:
      matrix:
        platform: [win, mac, linux]  # 构建三个平台

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # 你可以指定 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build-only  # 打包 Vue 应用，确保你的 package.json 中有此脚本

      - name: Build Electron app
        run: npm run build  # 先打包 Vue 后再打包 Electron

      - name: Install electron-builder
        run: npm install electron-builder --save-dev

      - name: Build and Publish Electron app
        run: |
          npx electron-builder --${{ matrix.platform }} --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用 GitHub Token 进行发布
