name: Build Vue and Electron App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [win, mac, linux]  # 定义要构建的平台

    runs-on: ${{ matrix.platform == 'win' && 'windows-latest' || matrix.platform == 'mac' && 'macos-latest' || 'ubuntu-latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Vue
        run: npm run build-only

      - name: Build Electron
        env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 添加 GH_TOKEN 环境变量
        run: |
          if [ ${{ matrix.platform }} == 'win' ]; then
            npx electron-builder --win
          elif [ ${{ matrix.platform }} == 'mac' ]; then
            npx electron-builder --mac
          elif [ ${{ matrix.platform }} == 'linux' ]; then
            npx electron-builder --linux
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-build-artifacts
          path: build/**
